# Generated by Django 4.2.2 on 2023-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otregister',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('casenumber', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CaseNumber', max_length=15, null=True)),
                ('casename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CaseName', max_length=50, null=True)),
                ('casestatus', models.IntegerField(blank=True, db_column='CaseStatus', null=True)),
                ('hospitalid', models.IntegerField(db_column='HospitalId')),
                ('surgerydate', models.DateTimeField(blank=True, db_column='SurgeryDate', null=True)),
                ('patientname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PatientName', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('gender', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Gender', max_length=1, null=True)),
                ('speciality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Speciality', max_length=100, null=True)),
                ('surgeonid', models.IntegerField(blank=True, db_column='SurgeonId', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=15, null=True)),
                ('patientdiagnostics', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PatientDiagnostics', max_length=300, null=True)),
                ('bookfavphysician', models.IntegerField(blank=True, db_column='BookFavPhysician', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('hospitalotroomid', models.IntegerField(blank=True, db_column='HospitalOTRoomId', null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createdon', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedon', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
            ],
            options={
                'db_table': 'OTRegister',
                'managed': False,
            },
        ),
    ]
